name: build-container
on:
  - push
  - workflow_dispatch

jobs:
  simple-ubuntu:
    strategy:
      matrix:
        ubuntu_version: [16.04, 18.04, 20.04, 22.04, latest]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./SimpleUbuntu
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu_version }}
          push: true
          tags: ghcr.io/tonypepebear/ssh-dev-ubuntu:${{ matrix.ubuntu_version }}
